# .goreleaser.yml
# Build customization
builds:
  - binary: baku
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      
archive:
  format: zip